# Generated by Django 4.1.7 on 2023-03-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='outlay',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='outlay',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
