# Generated by Django 4.1.7 on 2023-03-13 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outlay', '0003_alter_outlay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
