# Generated by Django 4.1.7 on 2023-03-13 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlay', '0004_alter_outlay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
