# Generated by Django 4.1.7 on 2023-03-13 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlay', '0005_alter_outlay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 11, 45, 35, 890397)),
        ),
    ]
